login: &login
  adapter: postgresql
  username: calendar
  password: 2511
  host: localhost
  encoding: UTF8

development:
  <<: *login
  database: calendar

test:
  <<: *login
  database: calendar_test

production:
  <<: *login
  database: calendar_production

